version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: skin4all
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./Back-end
      dockerfile: Dockerfile
    container_name: skin4all_backend
    environment:
      NODE_ENV: development
      PORT: 5000
      DB_HOST: mongodb
      DB_PORT: 27017
      DB_USERNAME: admin
      DB_PASSWORD: password123
      DB_NAME: skin4all
    ports:
      - "5001:5000"
    depends_on:
      - mongodb
    volumes:
      - ./Back-end:/app
      - backend_node_modules:/app/node_modules
    command: npm run start:dev

  frontend:
    build:
      context: ./Front-end
      dockerfile: Dockerfile
    container_name: skin4all_frontend
    environment:
      NODE_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - ./Front-end:/app
      - frontend_node_modules:/app/node_modules
    command: npm run dev

volumes:
  mongo-data:
  backend_node_modules:
  frontend_node_modules: