version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: skin4all_mongodb
    restart: unless-stopped
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: skin4all
    volumes:
      - mongo_data:/data/db
    networks:
      - skin4all_network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: skin4all_backend
    environment:
      NODE_ENV: development
      PORT: 5000
      DB_HOST: mongodb
      DB_PORT: 27017
      DB_USERNAME: admin
      DB_PASSWORD: password123
      DB_NAME: skin4all
    ports:
      - '5001:5000'
    depends_on:
      - mongodb
    networks:
      - skin4all_network
    volumes:
      - .:/app
    command: npm run start:dev

volumes:
  mongo_data:


networks:
  skin4all_network:
    driver: bridge
