import { UserDto } from '../../common/dtos/user.dto';

export const MOCK_USERS: UserDto[] = [
  {
    id: 'u1',
    name: 'Sofía Navarro',
    avatarUrl: 'https://i.pravatar.cc/80?img=29',
    email: 'sofia@skin4all.com',
    login: 'sofian',
    password: 'skin4all123',
    city: 'Madrid, Spain',
    skinType: 'Combination / Sensitive',
    bio: 'Focused on keeping my barrier healthy with lightweight hydration and gentle actives.',
    reviewCount: 18,
    favoriteProductIds: ['1', '5', '12', '14'],
    createdRoutineIds: ['r1', 'r7'],
  },
  {
    id: 'u2',
    name: 'Alex Romero',
    avatarUrl: 'https://i.pravatar.cc/80?img=22',
    email: 'alex@skin4all.com',
    login: 'alexr',
    password: 'skin4all123',
    city: 'Barcelona, Spain',
    skinType: 'Dry / Dehydrated',
    bio: 'Night routine fan, always looking for rich textures and effective anti-aging products.',
    reviewCount: 12,
    favoriteProductIds: ['1', '4', '10', '15'],
    createdRoutineIds: ['r2', 'r9'],
  },
  {
    id: 'u3',
    name: 'Jamie López',
    avatarUrl: 'https://i.pravatar.cc/80?img=36',
    email: 'jamie@skin4all.com',
    login: 'jamiel',
    password: 'skin4all123',
    city: 'Ciudad de México, Mexico',
    skinType: 'Textured / Resilient',
    bio: 'I keep things simple: exfoliate strategically, hydrate deeply, repeat consistently.',
    reviewCount: 9,
    favoriteProductIds: ['3', '6', '11', '14'],
    createdRoutineIds: ['r6'],
  },
  {
    id: 'u4',
    name: 'Marcos Díaz',
    avatarUrl: 'https://i.pravatar.cc/80?img=14',
    email: 'marcos@skin4all.com',
    login: 'markd',
    password: 'skin4all123',
    city: 'Buenos Aires, Argentina',
    skinType: 'Oily / Acne-prone',
    bio: 'Sharing routines that balance oil control with a healthy, calm skin barrier.',
    reviewCount: 15,
    favoriteProductIds: ['2', '5', '11', '13'],
    createdRoutineIds: ['r3', 'r8'],
  },
  {
    id: 'u5',
    name: 'Chloe Vargas',
    avatarUrl: 'https://i.pravatar.cc/80?img=41',
    email: 'chloe@skin4all.com',
    login: 'chloev',
    password: 'skin4all123',
    city: 'Lima, Peru',
    skinType: 'Sensitive / Dry',
    bio: 'If a product helps calm redness and lock in moisture, it probably ends up in my shelfie.',
    reviewCount: 11,
    favoriteProductIds: ['1', '6', '10', '14'],
    createdRoutineIds: ['r4', 'r10'],
  },
  {
    id: 'u6',
    name: 'Nina Paredes',
    avatarUrl: 'https://i.pravatar.cc/80?img=44',
    email: 'nina@skin4all.com',
    login: 'ninap',
    password: 'skin4all123',
    city: 'Bogotá, Colombia',
    skinType: 'Dull / Combination',
    bio: 'I love antioxidant-heavy morning routines that brighten without overloading the skin.',
    reviewCount: 14,
    favoriteProductIds: ['2', '8', '12', '15'],
    createdRoutineIds: ['r5'],
  },
];
