name: Tests Front-end
on:
  push:
    branches: [ main, master ]
    paths: [ 'Front-end/**' ]
  pull_request:
    branches: [ main, master ]
    paths: [ 'Front-end/**' ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm install -g pnpm && pnpm install
      working-directory: ./Front-end
    - name: Install Playwright Browsers
      run: pnpm exec playwright install --with-deps
      working-directory: ./Front-end
    - name: Run Playwright tests
      run: pnpm exec playwright test
      working-directory: ./Front-end
    - name: Run Unit tests
      run: pnpm run test:unit
      working-directory: ./Front-end
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
